import Head from 'next/head'
import { ConnectButton } from '@rainbow-me/rainbowkit'

export default function Home() {
  return (
    <>
      <Head>
        <title>RainbowKit Next.js Example App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main className="flex min-h-screen items-center justify-center">
        <ConnectButton />
      </main>
    </>
  )
}
